Repository HZ-HBOICT-Y2-2425/uvc-project-frontend-team-1-greedy-goblins, pull requests merged in 2024-12, with the labels that each got.

#53 Feature market page
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/location/[id]/+page.svelte
  src/routes/profile/+page.svelte
Labels: User story, Frontend

#56 geolocation toegevoegd en code refactor
  src/routes/co2/+page.svelte
  src/routes/co2/co2Calculator.js
  src/routes/co2/userLocation.js
Labels: enhancement, Frontend

#64 brekent distance tussen user en HZ groene woud automatisch
  src/routes/co2/+page.svelte
  src/routes/co2/distanceCalculator.js
Labels: Frontend

#75 profile page aangepast
  src/routes/+layout.svelte
  src/routes/oudeBestellingen/+page.svelte
  src/routes/oudeBestellingen/co2Calculator.js
  src/routes/oudeBestellingen/distanceCalculator.js
  src/routes/oudeBestellingen/productEmissionCalculator.js
  src/routes/oudeBestellingen/userLocation.js
  src/routes/profile/+page.svelte
Labels: Frontend

#74 laatste paar aanpassingen calculator
  src/lib/stores/orderDataStore.js
  src/routes/oudeBestellingen/+page.svelte
Labels: Frontend

#76 Feature graph
  package-lock.json
  package.json
  src/lib/stores/graphDataStore.js
  src/routes/co2Graph/+page.svelte
  src/routes/oudeBestellingen/+page.svelte
  src/routes/profile/+page.svelte
Labels: User story, Frontend

#78 Feature map
  src/routes/kaart/+page.svelte
Labels: User story, Frontend

#79 Add orders
  src/lib/components/Products.svelte
  src/lib/stores/cartStore.js
  src/lib/stores/orderDataStore.js
  src/lib/stores/productsEmissionStore.js
  src/routes/+layout.svelte
  src/routes/co2Graph/+page.svelte
  src/routes/location/[id]/+page.svelte
  src/routes/location/placeOrder.js
  src/routes/oudeBestellingen/+page.svelte
  src/routes/oudeBestellingen/productEmissionCalculator.js
Labels: User story, Frontend

#83 heb toegevoegd dat je gegevens naar betaalpagina wordt gesturud
  src/lib/components/Products.svelte
  src/routes/betaalpagina/+page.svelte
Labels: Frontend

#90 Feature kaarten
  src/lib/components/MarketBox.svelte
  src/lib/components/Products.svelte
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/betaalpagina/+page.svelte
  src/routes/collection/+page.svelte
  src/routes/location/[id]/+page.svelte
  src/routes/profile/+page.svelte
  static/kaarten/groente/Groente_wortel.png
  static/kaarten/uncollected/Fruit_uncollected.png
  static/kaarten/uncollected/Groente_uncollected.png
  static/kaarten/uncollected/Vis_uncollected.png
  static/kaarten/uncollected/Vlees_uncollected.png
  static/kaarten/uncollected/Zuivel_uncollected.png
Labels: Frontend

#89 Updates to package.json
  package-lock.json
Labels: enhancement
