Repository HZ-HBOICT-Y2-2425/uvc-project-frontend-team-1-greedy-goblins, pull requests merged in 2025-01, with the labels that each got.

#101 Shopping cart
  src/lib/components/Products.svelte
  src/lib/components/ShoppingCart.svelte
  src/lib/stores/cartStore.js
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/betaalpagina/+page.svelte
  src/routes/betaalpagina/placeOrder.js
  src/routes/location/placeOrder.js
Labels: enhancement

#97 styling plaatjes in marketvoerview
  package-lock.json
  src/routes/location/[id]/+page.svelte
Labels: enhancement

#103 Button verwijderd
  src/lib/components/Products.svelte
Labels: Frontend

#111 Heb nu toegevoegd dat je de afstand op de home page ziet van alle win…
  src/lib/calculators/co2Calculator.js
  src/lib/calculators/distanceCalculator.js
  src/lib/calculators/productEmissionCalculator.js
  src/lib/calculators/userLocation.js
  src/lib/components/MarketBox.svelte
  src/lib/index.js
  src/lib/stores/marketDistances.js
  src/routes/+page.svelte
  src/routes/oudeBestellingen/+page.svelte
  src/routes/oudeBestellingen/userLocation.js
Labels: enhancement

#117 files ignored
  eslint.config.js
  package-lock.json
  src/lib/components/Products.svelte
  src/lib/components/ShoppingCart.svelte
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/betaalpagina/+page.svelte
  src/routes/collection/+page.svelte
  src/routes/location/[id]/+page.svelte
  src/routes/oudeBestellingen/+page.svelte
  src/routes/profile/+page.svelte
Labels: bug
